version: '2'

services:
  zoo1:
    image: wurstmeister/zookeeper
    restart: unless-stopped
    hostname: zoo1
    ports:
      - "2181:2181"
    container_name: pipeline-zookeeper


  kafka1:
    image: confluentinc/cp-kafka:4.0.0
    hostname: kafka1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka1:9092"
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zoo1
    container_name: pipeline-kafka


  kafka-producer:
    build: ./kafka-producer
    depends_on:
      - kafka1
    container_name: pipeline-kafka-producer


  mysql:
    image: mysql:5.6.34
    restart: always
    environment:
      MYSQL_DATABASE: "sales_data_pipeline"
      MYSQL_ROOT_PASSWORD: "233"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    command: --init-file /tmp/create_db.sql
    volumes:
      - ./mysql/create_db.sql:/tmp/create_db.sql
    ports:
      - "3306:3306"
    container_name: pipeline-mysql
